# Docker Compose configuration for Math Agent dev container
#
# Services:
#   - devcontainer: Main development environment with mounted workspaces
#   - otlp: OpenTelemetry collector for telemetry data (optional)
#
# Volumes:
#   - gh-auth: Named volume for GitHub CLI credentials
#   - claude-config: Named volume for Claude CLI configuration
#   - gemini-config: Named volume for Gemini CLI configuration
#   - cloudflared-config: Named volume for Cloudflare tunnel credentials
#
# Note: To disable OTLP telemetry, add to devcontainer.json: "runServices": ["devcontainer"]

volumes:
  gh-auth:
  claude-config:
  gemini-config:
  cloudflared-config:

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/math-agent:cached
      - gh-auth:/home/codespace/.config/gh
      - claude-config:/home/codespace/.claude
      - gemini-config:/home/codespace/.gemini
      - cloudflared-config:/home/codespace/.cloudflared
    command: sleep infinity
    environment:
      - CLAUDE_CODE_ENABLE_TELEMETRY=1
      - CLAUDE_CONFIG_DIR=/home/codespace/.claude
      - WORKSPACE_PATH=/workspaces/math-agent
    depends_on:
      - otlp-collector

  otlp-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    environment:
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - HONEYCOMB_DATASET=${HONEYCOMB_DATASET:-math-agent}
    ports:
      - "4317:4317"
      - "4318:4318"